# Generated by Django 5.1.7 on 2025-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('time', models.TimeField()),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('city', 'time', 'user_name')},
            },
        ),
    ]
